FROM python:3

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install psycopg2

# define the port number the container should expose
EXPOSE 5432

# run the command
CMD ["python", "./app.py"]